#! /bin/sh
 
WALLPAPER=$HOME/Wallpapers/2.jpg

sxhkd &
picom --vsync --experimental-backend &
dunst -config $HOME/.config/dunst/dunstrc &
feh --bg-fill $WALLPAPER &
xrdb -merge ~/.cache/wal/colors.Xresources
wal -o $HOME/Scripts/dunst_ln.sh -i $WALLPAPER
wpg -a $WALLPAPER
#python3 $HOME/Scripts/wal_steam/wal_steam.py -w -d -s $HOME/.local/share/Steam/skins
polybar main &
#exec --no-startup-id feh --bg-fill ~/Wallpapers/1.jpg
bspc monitor -d 1 2 3 4 5 6 7 8 9 10
#bash /home/localcc/Scripts/SpaceChanger.sh &
bspc config border_width         0
bspc config window_gap          6
bspc config top_padding		18

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config ignore_ewmh_focus true

setxkbmap pl,ru
setxkbmap -option 'grp:win_space_toggle'
kitty &
#declaring rules
bspc rule -a discord desktop=^9
bspc rule -a Google-chrome desktop=^2
#launching applications
discord & 
google-chrome-stable &
